### ISSUE TITLE
Error: TypeError Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by GalaxymaxiS** [negue/meme-box#548]
### Message

> TypeError Cannot read properties of undefined (reading 'name')

### Context

> when i go to change the ms of an video (animation setting) he get this error

### Stack

```
TypeError: Cannot read properties of undefined (reading 'name')
    at u._next (http://IPADDRESS:6363/screens-screen-route-screen-route-module-es2015.a3e7dd02f51b885e091e.js:1:593)
    at u.__tryOrUnsub (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:128284)
    at u.next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:127505)
    at l._next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:126676)
    at l.next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:126450)
    at c._next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:324570)
    at c.next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:126450)
    at o._next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:779642)
    at o.next (http://IPADDRESS:6363/main-es2015.9228e9aa69f510a5f956.js:1:126450)
    at o._next (http://IPADDRESS:6IPADDRESS-es2015.9228e9aa69f510a5f956.js:1:653668)
```

### Version:

> 2022.1.1 - 4be1476

**Comment by negue** [comment]
Hey!

I'll see if I can pinpoint why that even throws an error 

from the first read its like it cant find an action (in this case the video) - then trying to read name from it... while trying to change the animation ms.... (which doesn't change anything in this sorts, only changes the preview animation) 

And that definitely throws the error right after you change the animation ms?

**Comment by GalaxymaxiS** [comment]
I try to go into detail:
when I'm in the screens section and I edit the animation immediately after changing the ms of the video, this error appears, but it's bizarre that the video exists.

In fact, even after the error comes out and I update the setting, it works for me (that is, the trigger, the video and the animation start), I just thought I'd report the situation

> Hey!
> 
> I'll see if I can pinpoint why that even throws an error
> 
> from the first read its like it cant find an action (in this case the video) - then trying to read name from it... while trying to change the animation ms.... (which doesn't change anything in this sorts, only changes the preview animation)
> 
> And that definitely throws the error right after you change the animation ms?
